site_name: FastAPI with async and Postgresql
site_url: https://vincedgy.github.io/fastapi-async-with-postgresql/
site_author: vincedgy
copyright: MIT

repo_url: https://github.com/vincedgy/fastapi-async-with-postgresql
edit_uri: tree/main/docs
repo_name: GitHub

nav:
    - Home: index.md
    - About: about.md
theme:
    name: mkdocs
    extra_css:
        - css/extra.css
    highlightjs: true
    hljs_languages:
        - yaml
        - python
        - shell
        - sql